### ISSUE TITLE
Limit distance to outgoing edges

### ISSUE THREAD

**Issue by arjunattam** [jumattos/lsif-util#4]
I'm using the tool to visualize an LSIF file. The center vertex of the graph (let's call this _v_ for now) is a direct descendent of the `project` vertex. I wanted to see the descendent tree of _v_, upto a distance of 2/3. However, because _v_ is a child of `project`, running the tool with `-d 2` creates a really large output, since all direct descendants of `project` are added to the graph.

It would be useful to be able to restrict the distance to only the outgoing edges, and not extend it to parents. This could be another flag for the tool, but I'm not sure if that is the best interface to implement this (want to restrict the flags as much as possible). Would love to hear other suggestions

**Comment by jumattos** [comment]
Thank you for opening this issue. I agree; the current output is pretty convoluted. I can see two approaches that do the same thing, basically:

1. Adding a `--childrenOnly` flag to avoid showing the parent and sibilings
2. Adding a `--root` flag that specifies which vertex will be the root of the graph

We could differentiate between vertices that are "root" (we only want to see children) from the ones that we are generally interested in (current behavior). I would have to think about a simpler way of explaining this, of course, because the last thing I want to do is adding too much complexity to the tool.

**Comment by arjunattam** [comment]
Closing this as by design for now, and will evaluate once we have more usage.
