### ISSUE TITLE
Add tslint to normalize the code format

### ISSUE THREAD

**Issue by jdneo** [jumattos/lsif-util#8]

**Comment by jumattos** [comment]
This is a good suggestion. I wrote this code a bit too quickly, and I think some refactoring/cleaning up is needed. Will work on that.

**Comment by jumattos** [comment]
It took me a whole afternoon, but I just merged PR #14, adding TSLint and doing the necessary code cleanup to adequate to it. I do think the code is much clearer now, but since I don't have any unit tests set up, I am not a 100% sure this refactor didn't introduce any regressions. Let me know if you encounter any errors!

**Comment by jdneo** [comment]
Cool, thank you @jumattos!
